name: Build and push api image to registry

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-api:
    uses: code4romania/.github/.github/workflows/build-push-image.yml@main
    with:
      images: code4romania/rezultate-vot-api
      dockerfile: ./src/ElectionResults.API/Dockerfile
      context: ./src
    secrets:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
